<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>false</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.NET" Version="3.1.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuicPunch\QuicPunch.csproj" />
    <ProjectReference Include="..\Wintun\Wintun.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="wintun.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="wwwroot\**" />
  </ItemGroup>

</Project>
