<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>False</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.NET" Version="3.1.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuicPunch\QuicPunch.csproj" />
    <ProjectReference Include="..\QuicPunch.Vpn\QuicPunch.Vpn.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="QuicPunchTests.Protocols" />
    <Using Include="QuicPunchTests.Settings" />
    <Using Include="QuicPunchTests.Helpers" />
    <Using Include="QuicPunchTests.WebUi" />
  </ItemGroup>

  <ItemGroup>
    <None Update="wintun.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="wwwroot\**" />
  </ItemGroup>

</Project>
