name: CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '11.0.x'
          dotnet-quality: preview

      - name: Restore dependencies
        run: dotnet restore QuicPunch.slnx

      - name: Build Solution
        run: dotnet build QuicPunch.slnx --no-restore -c ${{ matrix.configuration }}
